Implement way to move items between equipment and backpack #152
neu5-przenz-games/the-game pull request #174
Opened 2021-06-17 10:48 UTC by neu5

2021-06-17 12:36 UTC, neu5 commented on client/events/sockets.js
> +  }) => {
Maybe some different name. ItemNameFromBackpack?

2021-06-17 12:36 UTC, neu5 commented on client/index.html
> +                            move to backpack
Shouldn't be visible for items in the backpack

2021-06-17 12:36 UTC, neu5 commented on client/index.html
> +                            wear it
Should be visible for wearable items only

2021-06-17 12:36 UTC, neu5 commented on client/ui/profile.js
> +        this.whichItemFromBackpack = whichItemFromBackpack;
Should be conditional, it applies to items in the backpack only

2021-06-17 12:36 UTC, neu5 commented on client/ui/profile.js
> +      if (action === "close") {
Could be done better. Use mapping pattern.

2021-06-17 12:36 UTC, neu5 commented on server/index.js
> +        if (actionName === "move to backpack") {
Use mapping pattern

2021-06-17 13:15 UTC, przenz requested changes

2021-06-17 13:15 UTC, przenz commented on client/events/sockets.js
> +    whichItemFromBackpack,
It could be shorter: `itemFromBackpack` or even `backpackItem`

2021-06-17 13:15 UTC, przenz commented on client/ui/profile.js
> +    this.whichItemFromBackpack = "";
` = null` ?

2021-06-17 13:15 UTC, przenz commented on client/ui/profile.js
> +      } else if (action === "move to backpack") {
All actions should be defined elsewhere and included here and in  `server/index.js`. Probably not doable for the `index.html` file, but should be updated there accordingly.

2021-06-17 13:15 UTC, przenz commented on client/styles/styles.css
> +.equipment__item,
Cosmetics: add `user-select: none` so it will be not possible to select the text.

2021-06-17 13:15 UTC, przenz commented on client/ui/profile.js
> +        this.itemName = itemName;
It seems that this is used for holding selected item, please rename to reflect it's role, `selectedItemName` ?

2021-06-17 13:15 UTC, przenz commented on client/ui/profile.js
> +  showItemActions() {
It would be nice to hide undoable actions, like "wear it" when it's already equipped, I have crated an issue for it: #175

2021-06-17 13:15 UTC, przenz commented on client/ui/profile.js
> +        this.hideItemActions();
`        this.hideItemActions();` is called in each of `if` case, move it outside

2021-06-17 13:15 UTC, przenz commented on server/gameObjects/Player.js
> +      this.removeFromEquipment(itemName, whichItemFromBackpack)
This operation should be atomic, in case `addToBackpack` succeeds, but `removeFromUquipement` fails we end up with bonus item in backpack.

2021-06-17 13:15 UTC, przenz commented on server/gameObjects/Player.js
> +  addToEquipment(newItem) {
It's really hard to understand what's going on in here, please do  some name refactoring:
- `ITEMS` holds actually item categories
- `item` is actually item category
- Create something like `getItemCategory()` which will extract category from `ITEMS`

2021-06-17 13:15 UTC, przenz commented
Backpack item shows "undefined" name when clicked in equipment.

2021-06-18 08:03 UTC, neu5 commented on client/events/sockets.js
> +    whichItemFromBackpack,
The name is all wrong :D 
It's actually the item type from the equipment, like `weapon`, `helmet` or `shield`

2021-06-18 08:59 UTC, neu5 commented on client/styles/styles.css
> +.equipment__item,
Why?

2021-06-18 09:17 UTC, przenz commented on client/styles/styles.css
> +.equipment__item,
![image](https://user-images.githubusercontent.com/2963266/122538318-b5a8b800-d026-11eb-95b4-f52e5acf7fef.png)

2021-06-18 10:31 UTC, neu5 commented on client/styles/styles.css
> +.equipment__item,
ok, and what is wrong with that? :)

2021-06-18 10:36 UTC, przenz commented on client/styles/styles.css
> +.equipment__item,
I hate it

2021-06-18 10:40 UTC, przenz approved these changes

2021-06-18 10:44 UTC, merged